apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loggy
  labels:
    k8s-app: loggy
spec:
  selector:
    matchLabels:
      name: loggy
  template:
    metadata:
      labels:
        name: loggy
    spec:
      containers:
      - name: loggy
        image: kwsorensen/loggy:latest
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 30